### ISSUE TITLE
cannot edit settings

### ISSUE THREAD

**Issue by faithhealer** [DASPRiD/google-form-telegram-bot-notifications#2]
hi, no matter what I try, I cannot access the bot settings/text edit. i can just open the information/help page

**Comment by lilloscar** [comment]
Your app script is working good throughout a lot of time, is there one opportunity to add all the answers that were filled? Like the option in the Add-ons from Digital Inspiration like "Document Studio" to use this bracket {{All Answers}}?

**Comment by faithhealer** [comment]
I found what the problem was. you have to actually log out of all gmail accounts and only login with the one connected in order to access the edit script option. that is slightly annoying but probably a google workplace issue, not a script issue. sorry for wasting your time.
